import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Lexend } from 'next/font/google'
import { Providers } from './redux/provider'
const Navbar = dynamic(() => import('./components/Navbar/Navbar'), { ssr: false })
import { GoogleOAuthProvider } from '@react-oauth/google'
import { GOOGLE_CLIENT_ID } from './utils/constants'

import './globals.css'


const font = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
